# This is a basic workflow to help you get started with Actions

name: Create a module repo

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      module-display-name:
        description: 'Enter the module Display name, like "Key vault".'
        required: true
        default: ''
      module-name:
        description: 'Enter a module name, like "keyvault" to create "terraform-azurerm-keyvault" repository.'
        required: true
        default: ''
      module-code:
        description: 'Enter the module code/prefix, like "kv".'
        required: true
        default: ''

env:
  ORG_NAME: embergertf
  REPO_PREFIX: terraform-azurerm
  REPO_NAME: $REPO_PREFIX-${{ github.event.inputs.module-name }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  CreateModuleRepo:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

      # Where are we?
      - name: Run pwd & ls
        run: |
          pwd
          ls -al

      # Replace tokens in Terraform files
      - uses: cschleiden/replace-tokens@v1
        name: Replace tokens in Terraform files
        with:
          files: '["**/*.tf"]'
        env:
          MODULENAME: '${{ github.event.inputs.module-name }}' #"application-insights"
          MODULEDISPLAYNAME: '${{ github.event.inputs.module-display-name }}' #"Application Insights"
          CREATIONDATE: "2023-06-20"
          MODULECODE: '${{ github.event.inputs.module-code }}' # "api"

      # Check result on 1 file
      - name: Check token replacement in 1 file
        run: cat ../tooling-template/module-repo-template/main.tf

      # Create the new GitHub repository
      - name: Creating module repository
        uses: f1lander/create-repository-action@v1.0.2
        id: create-repo
        with:
          name: '$REPO_NAME'
          org: '$ORG_NAME'
          private: false
          access-token: '${{ secrets.ORG_ADMIN_TOKEN }}'

      # Clone the new GitHub repository
      - name: Cloning module repository
        run: git clone https://github.com/$ORG_NAME/$REPO_NAME.git
